/**
 * Generate the service worker after a build, with every emitted asset listed
 * explicitly.
 *
 * The precache list is produced by walking dist/, so it cannot drift from what
 * was actually built — including the 7 MB engine binary and all twelve piece
 * SVGs. A hand-maintained list is how a PWA ends up "installed" but unable to
 * play a game on a plane.
 *
 * The worker is cache-first for everything and never falls back to the network,
 * because the app has no network dependency to fall back to.
 *
 * Usage: node tools/build-sw.mjs   (runs as part of `npm run build`)
 */
import { readdirSync, statSync, writeFileSync, readFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { createHash } from 'node:crypto';

const DIST = 'dist';

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

const files = walk(DIST)
  .map((f) => relative(DIST, f).split('\\').join('/'))
  .filter((f) => f !== 'sw.js')
  .sort();

// Version the cache by the content of everything in it, so a changed build
// replaces the old cache instead of serving a stale mixture.
const hash = createHash('sha256');
for (const file of files) hash.update(readFileSync(join(DIST, file)));
const version = hash.digest('hex').slice(0, 12);

const assets = ['./', ...files.map((f) => `./${f}`)];

const sw = `/* Generated by tools/build-sw.mjs. Do not edit. */
const CACHE = 'chess-coach-${version}';
const ASSETS = ${JSON.stringify(assets, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      // addAll fails the whole install if any single request fails, which is
      // what we want: a half-cached app that cannot play offline is worse than
      // an install that retries.
      await cache.addAll(ASSETS);
      await self.skipWaiting();
    })()
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(names.filter((n) => n !== CACHE).map((n) => caches.delete(n)));
      await self.clients.claim();
    })()
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return; // nothing off-origin is ours

  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);
      const hit = await cache.match(request, { ignoreSearch: true });
      if (hit) return hit;
      // A navigation to any in-scope path is the app shell.
      if (request.mode === 'navigate') {
        const shell = await cache.match('./');
        if (shell) return shell;
      }
      try {
        const response = await fetch(request);
        if (response.ok) cache.put(request, response.clone());
        return response;
      } catch {
        return new Response('Offline and not cached.', {
          status: 504,
          headers: { 'Content-Type': 'text/plain' },
        });
      }
    })()
  );
});
`;

writeFileSync(join(DIST, 'sw.js'), sw);
process.stdout.write(
  `wrote ${DIST}/sw.js — cache chess-coach-${version}, ${assets.length} entries\n`
);
for (const file of files) {
  const size = statSync(join(DIST, file)).size;
  if (size > 500_000) {
    process.stdout.write(`  large asset precached: ${file} (${(size / 1e6).toFixed(1)} MB)\n`);
  }
}
